# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SQLiteSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SQLite.swift', '~> 0.14.0'
end
